name: E2E Test

on:
  pull_request:
    branches: [main]

  push:
    branches: [main]

jobs:
  code:
    name: Test code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3.2.0
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        uses: bahmutov/npm-install@v1.8.20
        with:
          install-command: yarn --frozen-lockfile --check-files --silent

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          record: false
          build: yarn build
          start: yarn preview
          wait-on: 'http://127.0.0.1:4173'
